import {Inter} from "next/font/google"
import "../styles/index.scss";
const inter = Inter({ variable: "--font1", subsets: ["cyrillic"] });


export const metadata = {
  title: 'Олечка самая лучшая',
  description: 'Generated by Next.js',
}


export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body className={`${inter.variable}`}
        >
          <div className="layout">
              <header>
      
              </header>
              {children}
              <footer>
                
              </footer>
          </div>
        </body>
      </html>
    );
  }
  